#!/usr/bin/env bash

uvx ruff check
if [[ $? == 0 ]]; then
    printf "Good Commit\n"
else
    printf "Lint Issues! Please resolve before commiting.\n"
    printf "commit-msg hook failed (add --no-verify to bypass)\n"
    exit 1
fi

uv run pytest
if [[ $? == 0 ]]; then
    printf "Good Commit\n"
else
    printf "Test Issues! Please resolve before commiting.\n"
    printf "commit-msg hook failed (add --no-verify to bypass)\n"
    exit 1
fi
