name: Validate Source Code

on:
  pull_request:
    branches:    
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Linting Source Code - Python
      run: make lint

    - name: Testing Source Code - Python
      run: make test