name: Validate Source Code

on:
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Install the project
      run: uv sync --dev

    - name: Run tests
      run: uvx ruff check

    - name: Run tests
      run: uv run pytest tests
